server.port=9092
spring.application.name=ms-seguridad

# Conexión a SQL Server usando Autenticación de Windows
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bd_hasamy;integratedSecurity=true;encrypt=true;trustServerCertificate=true;
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect